/**
 * ArbClass This code is automatically generated by the MoBIT Tool
 * 
 * @author Everton Leandro *
 */
public class TestableLivro extends Livro {
	public boolean isInDisponivel() {
		return getState().equals("Disponivel");
	}

	public void setToDisponivel() {
	}

	public boolean isInReservado() {
		return getState().equals("Reservado");
	}

	public void setToReservado(String situation) {
		if (situation
				.equals("livro.compareDatas (livro.dataReserva, livro.hoje) = -1")) {
		} else {

		}

	}

	public boolean isInEmprestado() {
		return getState().equals("Emprestado");
	}

	public void setToEmprestado(String situation) {
		if (situation
				.equals("livro.compareDate(livro.daataEmprestimo, livro.hoje) = 1")) {
		} else {
			if (situation.equals("livro.existeReserva()")) {
			} else {

			}

		}

	}

	public boolean isInAtrasado() {
		return getState().equals("Atrasado");
	}

	public void setToAtrasado(String situation) {
		if (situation.equals("livro.existeReserva()")) {
		} else {

		}

	}
}
