
/** 
*ArbClass This code is automatically generated by the MoBIT Tool
		@author Everton Leandro
**
*/
 public  class TestableQuiz extends Quiz {  public  boolean isInReady (){return getState().equals("Ready");
}
 public  void setToReady (){}
 public  boolean isInPausing (){return getState().equals("Pausing");
}
 public  void setToPausing (){}
 public  boolean isInRunning (){return getState().equals("Running");
}
 public  void setToRunning ( String situation){if(situation.equals("!quiz.endedQuestions()")){
}else{
if(situation.equals("quiz.endedQuestions()")){
}else{

}


}

}
 public  boolean isInHelping (){return getState().equals("Helping");
}
 public  void setToHelping (){}
 public  boolean isInEnding (){return getState().equals("Ending");
}
 public  void setToEnding (){}
}





