
/** 
*ArbClass This code is automatically generated by the MoBIT Tool
		@author Everton Leandro
**
*/
 public  class TestingGerenciador extends Gerenciador {private  TestableLivro server = null;
private  LivroTester tester = null;
private  Verdict verdict = null;
  public  void setTester ( LivroTester t){tester = t;;
}
 public  void setServer ( TestableLivro s){server = s;;
}
 public  void performTest (){if((.server != null) && (.tester != null)){verdict = tester.executeTest(server);;

}else{

}

}
}





