
/** 
*ArbClass This code is automatically generated by the MoBIT Tool  
		@author Everton Leandro
**
*/
 public  class Arbiter  {private  Verdict verdict = null;
private  Verdict partialVerdict = null;
  public  void Arbiter (){partialVerdict = Verdict.pass;
verdict = Verdict.pass;
}
 public  Verdict getVerdict (){return verdict;
}
 public  void setVerdict ( boolean v,  int i){if(partialVerdict != Verdict.fail){if(v == true){partialVerdict = Verdict.pass
}else{
if(){partialVerdict = Verdict.fail
}else{
if(){partialVerdict = Verdict.inconclusive
}else{
partialVerdict = Verdict.error
}

}

}
;

}else{

}
;
}
 public  void definesPartialVerdict (){verdict = partialVerdict;
}
}
