
/** 
*OUT!<unnamed> This code is automatically generated by the MoBIT Tool
		@author Everton Leandro
**
*/
 public  class BIT.QuizTester  { TestableQuiz server = null;
private  Arbiter arbiter = null;
  public  Verdict executeTest ( TestableQuiz s){arbiter = new Arbiter();;
server = s;
  ;;
  ;;
  ;;
  ;;
  ;;
  ;;
  ;;
testCase1();
testCase2();
testCase3();
testCase4();
testCase5();
testCase6();
testCase7();
testCase8();
return arbiter.getVerdict();
}
 public  void testCase1 (  ,   ){;
arbiter.definesPartialVeredict();
}
 public  void testCase2 (){;
arbiter.definesPartialVeredict();
}
 public  void testCase3 (  ){;
arbiter.definesPartialVeredict();
}
 public  void testCase4 (  ){;
arbiter.definesPartialVeredict();
}
 public  void testCase5 (){;
arbiter.definesPartialVeredict();
}
 public  void testCase6 (  ,   ){;
arbiter.definesPartialVeredict();
}
 public  void testCase7 (){;
arbiter.definesPartialVeredict();
}
 public  void testCase8 (  ){;
arbiter.definesPartialVeredict();
}
}
