
/** 
*ArbClass This code is automatically generated by the MoBIT Tool
		@author Everton Leandro
**
*/
 public  class BIT.TestableQuiz extends BIT.Quiz {  public  boolean BIT.isInReady (){return BIT.getState().equals("Ready");
}
 public  void BIT.setToReady (){BIT.setState("Ready");
}
 public  boolean BIT.isInPausing (){return BIT.getState().equals("Pausing");
}
 public  void BIT.setToPausing (){BIT.setState("Pausing");
}
 public  boolean BIT.isInRunning (){return BIT.getState().equals("Running");
}
 public  void BIT.setToRunning (  ){if(.("!quiz.endedQuestions()")){
}else{
if(.("quiz.endedQuestions()")){
}else{

}
;

}
;
BIT.setState("Running");
}
 public  boolean BIT.isInHelping (){return BIT.getState().equals("Helping");
}
 public  void BIT.setToHelping (){BIT.setState("Helping");
}
 public  boolean BIT.isInEnding (){return BIT.getState().equals("Ending");
}
 public  void BIT.setToEnding (){BIT.setState("Ending");
}
}
