
/** 
*ArbClass This code is automatically generated by the MoBIT Tool
		@author Everton Leandro
**
*/
 public  class BIT.TestingQuizManager extends BIT.QuizManager {private  BIT.TestableQuiz BIT.server = null;
private  BIT.QuizTester BIT.tester = null;
private  BIT.Verdict BIT.verdict = null;
  public  void BIT.setTester ( BITQuizTester BIT.t){BIT.tester = BIT.t;
}
 public  void BIT.setServer ( BITTestableQuiz BIT.s){BIT.server = BIT.s;
}
 public  void BIT.performTest (){if(){BIT.verdict = BIT.tester.BIT.executeTest(BIT.server);

}else{

}
;
}
}
